const baseUrl = process.env.REACT_APP_IMAGE_URL || "http://localhost:4000";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";

export { FOLLOW_USER_SUCCESS, LOGIN_SUCCESS, LOGOUT_SUCCESS, baseUrl };
